### ISSUE TITLE
Build task [cov2ap] could not be resolved after version update

### ISSUE THREAD

**Issue by T0bbes** [cap-js-community/odata-v2-adapter#33]
We have just upgraded our package json to the latest versions and then our pipeline broke with the following error. We never defined any mtx/sidecars things. After downgrading to the previous version (1.11.12) everything works again. Is this a problem on our part or was a default value set incorrectly during the last update of this package? 

```
Error: Build task [cov2ap] could not be resolved - folder src [/home/vsts/work/1/s/mtx/sidecar] does not exist
    at BuildTaskProviderFactory._resolveTask (/home/vsts/work/1/s/node_modules/@sap/cds-dk/lib/build/buildTaskProviderFactory.js:122:19)
    at /home/vsts/work/1/s/node_modules/@sap/cds-dk/lib/build/buildTaskProviderFactory.js:102:39
    at Array.map (<anonymous>)
    at BuildTaskProviderFactory.resolveTasks (/home/vsts/work/1/s/node_modules/@sap/cds-dk/lib/build/buildTaskProviderFactory.js:102:22)
    at BuildTaskFactory.getTasks (/home/vsts/work/1/s/node_modules/@sap/cds-dk/lib/build/buildTaskFactory.js:37:52)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async BuildTaskEngine.processTasks (/home/vsts/work/1/s/node_modules/@sap/cds-dk/lib/build/buildTaskEngine.js:35:21)
    at async build (/home/vsts/work/1/s/node_modules/@sap/cds-dk/lib/build/index.js:19:16)
    at async Object.build (/home/vsts/work/1/s/node_modules/@sap/cds-dk/bin/build.js:123:5)
    at async Object.exec (/home/vsts/work/1/s/node_modules/@sap/cds-dk/bin/cds.js:54:16)

``` 
Part of our package.json (We're cleaning up right now...... ;) )
```javascript
    "engines": {
        "node": "^18.X"
    },
    "dependencies": {
        "@azure/ai-form-recognizer": "^5.0.0",
        "@azure/identity": "^3.3.0",
        "@cap-js-community/odata-v2-adapter": "1.11.12",
        "@sap-cloud-sdk/http-client": "^3.9.0",
        "@sap-cloud-sdk/resilience": "^3.9.0",
        "@sap-cloud-sdk/util": "^3.9.0",
        "@sap/cds": "^7.0.2",
        "@sap/cds-dk": "^7.0.2",
        "@sap/xssec": "^3.6.0",
        "axios": "^1.5.0",
        "express": "^4",
        "hdb": "^0.19.5",
        "passport": "^0.6.0",
        "pdf2pic": "^3.1.0",
        "pdfmake": "^0.2.7",
        "perf_hooks": "^0.0.1",
        "pdf-images": "^1.3.0"
    },
    "devDependencies": {
        "@sap/approuter": "^14.4.3",
        "@sap/hdi-deploy": "^4.6.1",
        "@sap/ui5-builder-webide-extension": "^1.1.9",
        "@sap/ux-specification": "^1.108.8",
        "@sap/ux-ui5-fe-mockserver-middleware": "1",
        "@sap/ux-ui5-tooling": "^1.10.1",
        "@ui5/cli": "^3.3.1",
        "@ui5/fs": "^3.0.4",
        "@ui5/logger": "^3.0.0",
        "axios": "^1.5.0",
        "cds-plugin-ui5": "^0.7.2",
        "eslint": "^8.44.0",
        "kill-port": "^2.0.1",
        "mbt": "^1.2.24",
        "perf_hooks": "^0.0.1",
        "prettier": "^3.0.0",
        "pretty-quick": "^3.1.3",
        "rimraf": "5.0.1",
        "sqlite3": "5.1.6",
        "standard": "^17.1.0",
        "ui5-task-zipper": "^0.8.5"
    },
```

**Comment by oklemenz2** [comment]
Thanks for reporting. I will have a look and try to provide a fix. 

Until then you can set option „cds.cov2ap.build: false“ to disable build task…

**Comment by oklemenz2** [comment]
Should be addressed by https://registry.npmjs.org/@cap-js-community/odata-v2-adapter/-/odata-v2-adapter-1.12.2.tgz
Please have a look.

**Comment by nils** [comment]
Hi @oklemenz2, unfortunately the problem persists for me.

Environment:
```
@cap-js/cds-typer: 0.16.0
@cap-js/db-to-csv: 0.0.1
@cap-js/postgres: 1.5.1
@cap-js/postgres-native-deployer: 1.0.0
@cap-js/sqlite: 1.5.1
@sap/cds: 7.7.0
@sap/cds-compiler: 4.7.6
@sap/cds-dk: 7.7.1
@sap/cds-dk (global): 7.3.2
@sap/cds-fiori: 1.1.0
@sap/cds-foss: 4.0.2
@sap/cds-indexer: 1.0.14
@sap/cds-mtxs: 1.16.0
@sap/eslint-plugin-cds: 2.6.5
Node.js: v18.19.1
home: /workspace/rct-letticia/node_modules/@sap/cds
rct: 1.0.0
```

The [change](https://github.com/cap-js-community/odata-v2-adapter/commit/728ccb60bb46ed737307d15a580f217b58a882ec#diff-abc8f6a58535fbae6adcdf1f8348cb6bed037902afdf5731f0070dd0cdb28753R15) you made in January does not have an effect because the exception is thrown by cap before the build plugin is even loaded.

I assume that there needs to be an adjustment to [cds-plugin.js](https://github.com/cap-js-community/odata-v2-adapter/blob/77dcbafd0e60ccedba9aae69aa1caa95ad62edcc/cds-plugin.js#L17) instead. The exception reported above is raised because there is no `mtx/sidecar` folder in my (non-mtx) environment.

The workaround `cds.cov2ap.build: false` works fine for the moment, though!

**Comment by oklemenz2** [comment]
Thanks for your feedback. I will check again, to make that more robust. stay tuned

**Comment by FabianBerr** [comment]
Hi together,
i can also confirm a build error. We also use a pipeline, but the local build in BAS is also not working.
It appears since version 1.12.6:

```
[2024-03-06 14:20:41]  INFO executing the "npx cds build --production" command...
.building project [/home/user/projects/mes-system], clean [true]
cds-dk [7.7.0], cds [7.7.0], compiler [4.7.6], home [/home/user/projects/mes-system/node_modules/@sap/cds]

{
  build: {
    target: 'gen',
    tasks: [
      { for: 'hana', src: 'db', options: { model: ['db', 'srv', 'app'] }},
      { for: 'nodejs', src: 'srv', options: { model: ['db', 'srv', 'app'] }},
      { for: 'cov2ap', src: 'mtx/sidecar', options: { model: ['db', 'srv', 'app', 'mtx/sidecar'] }}
    ]
  }
}

Error: Build task [cov2ap] could not be resolved - folder src [/home/user/projects/mes-system/mtx/sidecar] does not exist
    at BuildTaskProviderFactory._resolveTask (/home/user/projects/mes-system/node_modules/@sap/cds-dk/lib/build/buildTaskProviderFactory.js:127:19)
    at /home/user/projects/mes-system/node_modules/@sap/cds-dk/lib/build/buildTaskProviderFactory.js:107:39
    at Array.map (<anonymous>)
    at BuildTaskProviderFactory.resolveTasks (/home/user/projects/mes-system/node_modules/@sap/cds-dk/lib/build/buildTaskProviderFactory.js:107:22)
    at BuildTaskFactory.getTasks (/home/user/projects/mes-system/node_modules/@sap/cds-dk/lib/build/buildTaskFactory.js:37:52)
    at async BuildTaskEngine.processTasks (/home/user/projects/mes-system/node_modules/@sap/cds-dk/lib/build/buildTaskEngine.js:36:21)
    at async build (/home/user/projects/mes-system/node_modules/@sap/cds-dk/lib/build/index.js:19:16)
    at async Object.build (/home/user/projects/mes-system/node_modules/@sap/cds-dk/bin/build.js:123:5)
    at async Object.exec (/home/user/projects/mes-system/node_modules/@sap/cds-dk/bin/cds.js:54:16)
[2024-03-06 14:20:43] ERROR the "before-all"" build failed: could not execute the "npx cds build --production" command: exit status 1
```

in version 1.12.5 everything works fine:
```
cds-dk [7.7.0], cds [7.7.0], compiler [4.7.6], home [/home/user/projects/mes-system/node_modules/@sap/cds]

{
  build: {
    target: 'gen',
    tasks: [
      { for: 'hana', src: 'db', options: { model: ['db', 'srv', 'app'] }},
      { for: 'nodejs', src: 'srv', options: { model: ['db', 'srv', 'app'] }}
    ]
  }
}

.......done > wrote output to:
   gen/db/.build.js
   gen/db/Schema/TODO
   gen/db/package-lock.json
```

**Comment by oklemenz2** [comment]
This was a little oversight... Can you please check with version 1.12.7
https://github.com/cap-js-community/odata-v2-adapter/releases/tag/v1.12.7

**Comment by FabianBerr** [comment]
Fix worked, thank you 😊
